# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x10virtualassistant\"*\n\x17VirtualAssistantRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"+\n\x18VirtualAssistantResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2x\n\x10VirtualAssistant\x12\x64\n\x0bSendMessage\x12).virtualassistant.VirtualAssistantRequest\x1a*.virtualassistant.VirtualAssistantResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VIRTUALASSISTANTREQUEST._serialized_start=32
  _VIRTUALASSISTANTREQUEST._serialized_end=74
  _VIRTUALASSISTANTRESPONSE._serialized_start=76
  _VIRTUALASSISTANTRESPONSE._serialized_end=119
  _VIRTUALASSISTANT._serialized_start=121
  _VIRTUALASSISTANT._serialized_end=241
# @@protoc_insertion_point(module_scope)
